name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy flake8-docstrings pydantic

    - name: Analysing the code with flake8
      run: flake8 --docstring-convention google --ignore D212,W503  $(git ls-files 'slxjsonrpc/*.py')

    - name: Analysing the code with mypy
      run: mypy --strict --follow-imports=normal --python-version 3.7  $(git ls-files 'slxjsonrpc/*.py')
