name: test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11.4"]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox and any other packages
      run: pip install tox

    - name: Run tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
